### ISSUE TITLE
[Group Request] Create a new chapter request for Bihar, India

### ISSUE THREAD

**Issue by aryasoni98** [cncf/communitygroups#79]
### City or location name for your CNCG

Kubernetes & Cloud Native Bihar

### What country do you want to start your community group in?

India

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

My name is Arya Soni, and I work on open-source projects like Keptn, Kubespray, and cncf/website, which are all CNCF projects. I've been working as a DevOps Engineer for the past two years, and I've been involved in a number of Amazon projects with my firm and clients. My effort focuses on raising awareness about CNCF and cloud-native technology in my community. 

I am particularly interested in establishing a CNCF local chapter to increase awareness of CNCF, organise events, and encourage more people to join the community. My opinions are consistent with the CNCF credo, which seeks to make cloud-native technology widespread.

Name : Arya Soni, [Netaji Subhas University of Technology] (http://nsut.ac.in/)
Email : aryasoni98@gmail.com
Github: @aryasoni98
LinkedIn: https://www.linkedin.com/in/aryasoni/
CNCF Slack: Arya Soni

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

I have various individuals that might help me, but more with organising talks; if co-organizers are required, I am well provided.

Name : Ayush Kumar, [ABES Engineering College] (https://abes.ac.in/)
Email : [ayushknj3@gmail.com](mailto:ayushknj3@gmail.com)
Github: @Ayush7614
LinkedIn: https://www.linkedin.com/in/ayush-kumar-984443191/
CNCF Slack: Ayush Kumar

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Name : Shubhangi Gupta, [Netaji Subhas University of Technology] (http://nsut.ac.in/)
Email : [shubhigupta991@gmail.com](mailto:shubhigupta991@gmail.com)
Github: @shubhigupta991
LinkedIn: https://www.linkedin.com/in/shubhigupta991/
CNCF Slack: Shubhangi Gupta

_No response_

### What is your mission statement or objective for this new chapter?

Our mission is to spark a dynamic community ignited by the power of cloud-native technologies. We're all about connecting tech enthusiasts and professionals to exchange cutting-edge insights, hacks, and stories in the cloud tech sphere. Join us to dive into a world where beginners morph into experts, and every voice fuels the next wave of cloud innovation. Let's innovate, collaborate, and elevate the cloud experience together!

As the organizer of this new CNCF chapter, my mission is to raise awareness about CNCF and the cloud-native ecosystem, as well as cloud-native technologies in my area. I aim to engage the community, spread education among them, and foster a vibrant community that can lead to further advancements in CNCF and the cloud-native ecosystem. My objective is to create a thriving community of like-minded individuals who will contribute to future advancements in CNCF and the cloud-native ecosystem.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year
```[tasklist]
### Tasks
```

**Comment by aryasoni98** [comment]
@AudMonte01, Follow-up commit on this issue . Any update on this.

**Comment by AudMonte01** [comment]
Thank you for the ping @aryasoni98 - I have some comments/questions about geography based on where each of your LinkedIn profiles say you reside.
* Kanpur (where Ayush resides) seems to be an 11-hour drive to Bihar
* Gurgaon and New Delhi seem further (based on yours and Shubhangi's LinkedIn profiles)

With that, I would like to know how much time you each spend in Bihar?

**Comment by aryasoni98** [comment]
@AudMonte01 Actually, my hometown is Bihar, Begusarai, and Ayush also visits Bihar because his relatives live there. Shubhangi's mother's hometown is Patna.

Time spent: 2-3 months in a year.

Additionally, there is no open-source or tech community in my hometown. That's why I want to open a CNCF chapter there to foster a tech community. 

Noted: Arya Soni (me), Shubhangi Gupta, and Ayush Kumar live in Delhi, NCR.

**Comment by AudMonte01** [comment]
Thank you for this insight. Ideally the organizers of each chapter spend half the year or more in the chapter city due to our [standards of activity.](https://github.com/cncf/communitygroups/blob/main/README.md#community-group-inactivity). Please let me know if the time each of you spend there is staggared so responsibilities can be divided/shared throughout the year.

**Comment by aryasoni98** [comment]
@AudMonte01 I will primarily be based in the city throughout the year, as my job is remote and allows for flexibility. Ayush, who works as a Developer Relations (DevRel) professional for multiple organizations, will also spend significant time in the city. Shubhangi will be present during meetups, events, hackathons, and webinars.

**Comment by AudMonte01** [comment]
Thank you for this insight. I have started the chapter and added you as an organizer to start. You should have just received an automated welcome email from me.

@Ayush7614 and @shubhigupta991 - please comment agreeing to all of the above organizer terms and confirm that you have completed the above, open source inclusivity course (free, online and self-paced).

**Comment by aryasoni98** [comment]
@AudMonte01 Thank you for the update! I’m excited to get started as an organizer for the chapter. Looking forward to contributing and working together with everyone.

**Comment by shubhigupta991** [comment]
Thank you for the opportunity @AudMonte01. I agree to all of the above organiser terms and confirm that I have completed the open source inclusivity course.

**Comment by Ayush7614** [comment]
@AudMonte01 Thank you for the update! I’m excited to get started as an organizer for the chapter. I agree to all of the above organizer terms and confirm that I have completed the open-source inclusivity course. Looking forward to contributing and working together with everyone.

**Comment by aryasoni98** [comment]
@AudMonte01 Everyone has agreed to all of the above organizer terms and confirmed that the tasks have been completed.

Could you please let me know the next stage in the process for the chapter? Also, when can we expect the team to receive the organizer invitations?

**Comment by AudMonte01** [comment]
Thank you, @Ayush7614 and @shubhigupta991 - I have added you both as organizers to the chapter. You should have just received an automated welcome email. Please follow instructions there for next steps, and have at least 1 of you attend my office hour this Friday for best practices on how to get started. https://community.cncf.io/e/mjh9z7/

I will now close this issue.
